services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
    - ./frontend/runtime-env.js:/usr/share/nginx/html/env.js:ro
  db:
    image: mongo:latest
    container_name: url-shortener-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  redis:
    image: redis
    container_name: url-shortener-redis
    restart: always
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

volumes:
  mongodata: