services:
  db:
    image: postgres:latest
    container_name: url-shortener-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: url-shortener-redis
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

volumes:
  pgdata: