services:
  db:
    image: mongo:latest
    container_name: url-shortener-mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  redis:
    image: redis
    container_name: url-shortener-redis
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

volumes:
  mongodata: